steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
    '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/$_IMAGE_NAME',
    '-f', '$_DOCKERFILE_PATH',
    '.'
  ]
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/$_IMAGE_NAME'
options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
