apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gce-pipeline
serialPipeline:
  stages:
  - targetId: gce-dev
#    strategy:
#      canary:
#        customCanaryDeployment:
#          phaseConfigs:
#          - phaseId: "c50"
#            percentage: 50
#          - phaseId: "stable"
#            percentage: 100
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: gce-dev
customTarget:
  customTargetType: gce
deployParameters:
  customTarget/gceProject: chris-test1-475920
  customTarget/gceMigProject: chris-test1-475920
  customTarget/gceRegion: us-central1
  customTarget/gceMigRegion: us-central1
  customTarget/gceBackendServiceProject: us-central1
  customTarget/gceInstanceGroupManagerPath: mig.yaml
  customTarget/gceBackendService: dev-bs
  customTarget/gceInstanceGroupManager: dev-mig
  customTarget/gceCloudLoadBalancerURLMap: projects/chris-test1-475920/regions/us-central1/urlMaps/l7-ilb-map
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: gce-prod
customTarget:
  customTargetType: gce
deployParameters:
  customTarget/gceProject: chris-test1-475920
  customTarget/gceMigProject: chris-test1-475920
  customTarget/gceRegion: us-central1
  customTarget/gceMigRegion: us-central1
  customTarget/gceBackendServiceProject: us-central1
  customTarget/gceInstanceGroupManagerPath: mig.yaml
  customTarget/gceBackendServiceTemplatePath: backend-service.yaml
  customTarget/gceBackendService: prod-bs
  customTarget/gceInstanceGroupManager: prod-mig
  customTarget/gceCloudLoadBalancerURLMap: projects/chris-test1-475920/regions/us-central1/urlMaps/l7-ilb-map
