name: Continuous Integration
run-name: ${{ github.actor }} is running tests 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Run all the unit tests
        working-directory: .
        run: go test ./... -cover -v